import { test, expect, _electron as electron } from '@playwright/test';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve, dirname, basename } from 'node:path';

test('Kyro menus select roles with short cost notes and preserve message settings', async () => {
  const profile = await mkdtemp(join(tmpdir(), 'kyro-model-picker-'));
  let app;
  try {
    app = await electron.launch({ args: ['.', `--kyro-profile=${profile}`], env: { ...process.env, KYRO_DESKTOP_DEV: '0' } });
    const page = await app.firstWindow();
    const errors = [];
    page.on('pageerror', (error) => errors.push(error.message));
    const picker = page.locator('.team-trigger');
    const panel = page.getByRole('region', { name: 'Composition de l’équipe' });
    const draft = page.getByRole('textbox', { name: 'Votre message' });
    const settings = page.locator('.composer-preferences > summary');
    const settingsPanel = page.getByRole('region', { name: 'Réglages du message' });
    const roleTrigger = (label) => page.getByLabel(new RegExp(`^${label} :`));
    const choices = (label) => page.getByRole('group', { name: `Choix ${label.toLocaleLowerCase('fr')}`, exact: true });
    async function choose(label, model) {
      await roleTrigger(label).click();
      await choices(label).getByRole('button', { name: new RegExp(`^${model}`) }).click();
      await expect(roleTrigger(label)).toBeFocused();
      await expect(choices(label)).not.toBeVisible();
    }
    await draft.fill('Une idée <script>test</script>');
    await picker.focus();
    await picker.press('Enter');
    await expect(panel).toBeVisible();
    await expect(panel).toContainText('Modèles et nombre de sous-agents.');
    await expect(page.locator('.composer select')).toHaveCount(0);
    await expect(panel.locator('footer, table, .team-cost, .team-inheritance')).toHaveCount(0);
    await expect(roleTrigger('Orchestrateur')).toContainText('Nemotron 3 Ultra');
    await expect(roleTrigger('Sous-agents')).toContainText('Nemotron 3.5 Lightning');
    // Arrow keys open the custom menu and navigate; Enter commits, Escape closes only the nested menu.
    await roleTrigger('Orchestrateur').press('ArrowDown');
    await expect(choices('Orchestrateur').getByRole('button', { name: /^Nemotron 3 Ultra/ })).toBeFocused();
    await page.keyboard.press('ArrowDown');
    await expect(choices('Orchestrateur').getByRole('button', { name: /^Nemotron 3 Super/ })).toBeFocused();
    await page.keyboard.press('Enter');
    await expect(roleTrigger('Orchestrateur')).toContainText('Nemotron 3 Super');
    await expect(roleTrigger('Sous-agents')).toContainText('Nemotron 3.5 Lightning');
    await roleTrigger('Sous-agents').click();
    await expect(choices('Sous-agents')).toContainText('(≈ 4,4× le coût de Lightning)');
    await expect(choices('Sous-agents')).toContainText('(≈ 14,8× le coût de Lightning)');
    await roleTrigger('Sous-agents').press('End');
    await expect(choices('Sous-agents').getByRole('button', { name: /^Nemotron 3 Nano/ })).toBeFocused();
    await page.keyboard.press('Escape');
    await expect(panel).toBeVisible();
    await expect(choices('Sous-agents')).not.toBeVisible();
    await expect(roleTrigger('Sous-agents')).toBeFocused();
    await choose('Sous-agents', 'Nemotron 3 Super');
    await panel.getByRole('button', { name: 'Plus de sous-agents', exact: true }).click();
    await expect(panel.locator('output')).toHaveText('5');
    await expect(page.locator('.user-message')).toHaveCount(0);
    await picker.press('Escape');
    await expect(panel).not.toBeVisible();
    await expect(picker).toBeFocused();
    await picker.click();
    await roleTrigger('Orchestrateur').click();
    await draft.click();
    await expect(panel).not.toBeVisible();
    await picker.click();
    await expect(choices('Orchestrateur')).not.toBeVisible();
    await settings.click();
    await expect(panel).not.toBeVisible();
    await expect(settingsPanel.locator('footer')).toHaveCount(0);
    const accessDialog = page.getByRole('dialog', { name: 'Activer l’accès complet ?' });
    async function requestFullAccess() {
      await roleTrigger('Accès').click();
      await choices('Accès').getByRole('button', { name: /^Accès complet/ }).click();
      await expect(accessDialog).toBeVisible();
      await expect(accessDialog.getByRole('button', { name: 'Annuler', exact: true })).toBeFocused();
    }
    await requestFullAccess();
    await page.keyboard.press('Escape');
    await expect(accessDialog).not.toBeVisible();
    await expect(settingsPanel).toBeVisible();
    await expect(roleTrigger('Accès')).toBeFocused();
    await expect(roleTrigger('Accès')).toContainText('Demander l’approbation');
    await requestFullAccess();
    await accessDialog.getByRole('button', { name: 'Fermer la confirmation' }).click();
    await expect(roleTrigger('Accès')).toContainText('Demander l’approbation');
    await requestFullAccess();
    await accessDialog.getByRole('button', { name: 'Annuler', exact: true }).click();
    await expect(roleTrigger('Accès')).toContainText('Demander l’approbation');
    await requestFullAccess();
    await page.screenshot({ animations: 'disabled', path: '../../docs/suivi/preuves/desktop-access-design-20261004.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => accessDialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
    await accessDialog.getByRole('button', { name: 'Activer l’accès complet', exact: true }).scrollIntoViewIfNeeded();
    await page.screenshot({ animations: 'disabled', path: '../../docs/suivi/preuves/desktop-access-design-mobile-20261004.png' });
    await page.setViewportSize({ width: 1280, height: 1000 });
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.screenshot({ animations: 'disabled', path: '../../docs/suivi/preuves/desktop-access-design-dark-20261004.png' });
    await page.emulateMedia({ colorScheme: 'light' });
    await accessDialog.getByRole('button', { name: 'Activer l’accès complet', exact: true }).click();
    await expect(accessDialog).not.toBeVisible();
    await expect(roleTrigger('Accès')).toContainText('Accès complet');
    await choose('Accès', 'Approbation automatique');
    await expect(settingsPanel.locator('.preference-options').first().getByRole('button')).toHaveText(['Faible', 'Standard', 'Élevé', 'Maximum']);
    await settingsPanel.getByRole('button', { name: 'Élevé', exact: true }).click();
    await settingsPanel.getByRole('button', { name: '8k', exact: true }).click();
    await draft.click();
    await expect(settingsPanel).not.toBeVisible();
    await expect(draft).toHaveValue('Une idée <script>test</script>');
    await draft.press('Enter');
    const first = page.locator('.user-message').first();
    await expect(first).toContainText('Super · 5 Super · démo');
    await expect(first).toContainText('Approbation automatique · Élevé · 8k');
    await expect(first.locator('script')).toHaveCount(0);
    await picker.click();
    await choose('Orchestrateur', 'Nemotron 3 Ultra');
    await choose('Sous-agents', 'Nemotron 3.5 Lightning');
    for (let i = 0; i < 4; i++) await panel.getByRole('button', { name: 'Moins de sous-agents' }).click();
    await expect(panel.getByRole('button', { name: 'Moins de sous-agents' })).toBeDisabled();
    for (let i = 0; i < 31; i++) await panel.getByRole('button', { name: 'Plus de sous-agents', exact: true }).click();
    await expect(panel.getByRole('button', { name: 'Plus de sous-agents', exact: true })).toBeDisabled();
    await draft.click();
    await draft.fill('Deuxième message');
    await draft.press('Enter');
    await expect(first).toContainText('Super · 5 Super · démo');
    await expect(page.locator('.user-message').last()).toContainText('Ultra · 32 Lightning · démo');
    await page.setViewportSize({ width: 1280, height: 1000 });
    await picker.click();
    await roleTrigger('Orchestrateur').click();
    await page.screenshot({ animations: 'disabled', path: '../../docs/suivi/preuves/desktop-team-pricing-menu-20261004.png' });
    await picker.press('Escape');
    for (const width of [1000, 390, 320]) {
      await page.setViewportSize({ width, height: 844 });
      await picker.click();
      await roleTrigger('Sous-agents').click();
      await choices('Sous-agents').getByRole('button', { name: /^Nemotron 3 Nano/ }).click();
      await expect(roleTrigger('Sous-agents')).toContainText('Nemotron 3 Nano');
      const bounds = await panel.boundingBox();
      expect(bounds.x).toBeGreaterThanOrEqual(0);
      expect(bounds.x + bounds.width).toBeLessThanOrEqual(width);
      expect(bounds.y).toBeGreaterThanOrEqual((await page.locator('.topbar').boundingBox()).height + 8);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      if (width === 390) await page.screenshot({ animations: 'disabled', path: '../../docs/suivi/preuves/desktop-team-pricing-mobile-20261004.png' });
      await picker.press('Escape');
      await settings.click();
      await choose('Accès', 'Demander l’approbation');
      await settings.press('Escape');
    }
    await page.setViewportSize({ width: 1000, height: 680 });
    await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
    await picker.click();
    await roleTrigger('Sous-agents').click();
    await choices('Sous-agents').getByRole('button', { name: /^Nemotron 3.5 Lightning/ }).click();
    await page.screenshot({ animations: 'disabled', path: '../../docs/suivi/preuves/desktop-team-pricing-dark-20261004.png' });
    expect(errors).toEqual([]);
  } finally {
    await app?.close();
    const target = resolve(profile);
    if (dirname(target) !== resolve(tmpdir()) || !basename(target).startsWith('kyro-model-picker-')) throw new Error('Unexpected test profile path');
    await rm(target, { recursive: true, force: true });
  }
});
