FROM debian:bookworm-20260918-slim@sha256:3783cc01769c7b2b1b83a5c5ad96c815348e28ed7da68e2e3687004faa906251
RUN apt-get update && apt-get install --yes --no-install-recommends nftables util-linux ca-certificates curl && rm -rf /var/lib/apt/lists/*
COPY guard.sh /usr/local/bin/guard
ENTRYPOINT ["/bin/sh", "/usr/local/bin/guard"]
