// Exact P2 scope from docs/backend/partie-2/MANIFESTE.md, 2026-10-05.
// This list names contracts; it is not qualification evidence.
pub const COMPONENT_NAMES: &[(&str,&str)] = &[
    ("B001", "Fédération OpenID Connect"),
    ("B002", "Comptes locaux optionnels"),
    ("B003", "Connexion sans mot de passe"),
    ("B004", "Authentification renforcée"),
    ("B005", "Sessions"),
    ("B006", "Récupération de compte"),
    ("B007", "Comptes de service et clés API"),
    ("B008", "Rôles et permissions"),
    ("B009", "Autorisations contextuelles"),
    ("B010", "Révocation des accès"),
    ("B011", "Organisations et locataires"),
    ("B012", "Établissements et espaces"),
    ("B013", "Adhésions et invitations"),
    ("B014", "Groupes et équipes"),
    ("B015", "Propriété et délégation"),
    ("B016", "Profils et préférences"),
    ("B017", "Commentaires"),
    ("B018", "Mentions et abonnements"),
    ("B019", "Fil d’activité"),
    ("B020", "Partage temporaire"),
    ("B021", "Moteur de décision d’accès"),
    ("B022", "Capacités d’exécution"),
    ("B023", "Références de secrets"),
    ("B024", "Limitation de débit"),
    ("B025", "Validation des entrées"),
    ("B026", "Projection et masquage"),
    ("B027", "Journal d’audit de sécurité"),
    ("B028", "Rétention et purge"),
    ("B029", "Export des données personnelles"),
    ("B030", "Quotas de ressources"),
    ("B031", "Entités typées"),
    ("B032", "Relations et contraintes"),
    ("B033", "Transactions métier"),
    ("B034", "Concurrence optimiste"),
    ("B035", "Requêtes et pagination"),
    ("B036", "Migrations de schéma"),
    ("B037", "Historique de versions"),
    ("B038", "Brouillons et publication"),
    ("B039", "Cache applicatif"),
    ("B040", "Import de données"),
    ("B041", "Valeurs exactes"),
    ("B042", "Dates et fuseaux"),
    ("B043", "Prédicats métier"),
    ("B044", "Champs calculés"),
    ("B045", "Machines d’états"),
    ("B046", "Workflows durables"),
    ("B047", "Approbations"),
    ("B048", "Compensations métier"),
    ("B049", "Activation de fonctionnalités"),
    ("B050", "Configuration typée"),
    ("B051", "Idempotence"),
    ("B052", "File de travaux"),
    ("B053", "Planification"),
    ("B054", "Outbox transactionnelle"),
    ("B055", "Inbox et déduplication"),
    ("B056", "Reprises et quarantaine"),
    ("B057", "Webhooks entrants"),
    ("B058", "Webhooks sortants"),
    ("B059", "Client HTTP contrôlé"),
    ("B060", "Traitements par lots"),
    ("B081", "Téléversement de fichiers"),
    ("B082", "Métadonnées de documents"),
    ("B083", "Téléchargement protégé"),
    ("B084", "Transformations de médias"),
    ("B085", "Modèles de documents"),
    ("B086", "Extraction et OCR"),
    ("B087", "Contenu éditorial"),
    ("B088", "Taxonomies"),
    ("B089", "Versions et archives de fichiers"),
    ("B090", "Formats d’import et export"),
    ("B091", "Recherche textuelle"),
    ("B092", "Recherche sémantique"),
    ("B093", "Indexation de documents"),
    ("B094", "Réponses avec sources"),
    ("B095", "Extraction structurée par modèle"),
    ("B096", "Classification assistée"),
    ("B097", "Résumé assisté"),
    ("B098", "Validation humaine des résultats IA"),
    ("B099", "Conversation applicative"),
    ("B100", "Évaluation des fonctions IA"),
    ("B101", "Notifications internes"),
    ("B102", "Modèles de messages"),
    ("B103", "Préférences de notification"),
    ("B104", "Courriels transactionnels"),
    ("B105", "Messages mobiles"),
    ("B106", "Notifications push"),
    ("B107", "Flux SSE"),
    ("B108", "Canaux WebSocket"),
    ("B109", "Présence"),
    ("B110", "Messagerie d’équipe"),
    ("B111", "Catalogue de ressources"),
    ("B112", "Règles de disponibilité"),
    ("B113", "Créneaux et capacité"),
    ("B114", "Réservations"),
    ("B115", "Annulations et reports"),
    ("B116", "Liste d’attente"),
    ("B117", "Récurrence"),
    ("B118", "Affectation de ressources"),
    ("B119", "Accueil et présence"),
    ("B120", "Calendriers externes"),
    ("B121", "Catalogue de produits"),
    ("B122", "Tarifs et grilles"),
    ("B123", "Panier et devis"),
    ("B124", "Commandes"),
    ("B125", "Encaissement via prestataire"),
    ("B126", "Abonnements"),
    ("B127", "Documents de facturation"),
    ("B128", "Remboursements et avoirs"),
    ("B129", "Promotions"),
    ("B130", "Stocks et inventaires"),
    ("B131", "Contacts et organisations clientes"),
    ("B132", "Prospects et opportunités"),
    ("B133", "Tickets de support"),
    ("B134", "Projets et tâches"),
    ("B135", "Interventions et ordres de travail"),
    ("B136", "Temps et activité"),
    ("B137", "Dépenses et justificatifs"),
    ("B138", "Achats et fournisseurs"),
    ("B139", "Matériel et prêts"),
    ("B140", "Dossiers et formulaires métier"),
    ("B141", "Événements analytiques"),
    ("B142", "Agrégations"),
    ("B143", "Définition des indicateurs"),
    ("B144", "Tableaux de bord"),
    ("B145", "Rapports planifiés"),
    ("B146", "Exports volumineux"),
    ("B147", "Alertes métier"),
    ("B148", "Qualité des données"),
    ("B149", "Historique d’indicateurs"),
    ("B150", "Suivi de consommation"),
    ("B151", "Stockage compatible S3"),
    ("B152", "Messagerie électronique"),
    ("B153", "Prestataires de paiement"),
    ("B154", "Calendriers et agendas"),
    ("B155", "Cartographie et géocodage"),
    ("B156", "OAuth pour connecteurs"),
    ("B157", "Connecteurs REST typés"),
    ("B158", "Import de bases externes"),
    ("B160", "Outils MCP"),
    ("B161", "Spécification AppSpec"),
    ("B162", "Registre du catalogue"),
    ("B163", "Résolution de composition"),
    ("B164", "Compilateur déterministe"),
    ("B169", "Passerelle d’outils"),
    ("B171", "Supervision des sandboxes"),
    ("B172", "Vérification indépendante"),
    ("B173", "Artefacts et provenance"),
];
